# Send format of xkcd message events. Defaults to 'split'.
# Mode 'split' sends the image and alt text as separate events. Mode 'inline'
# sends a text message with the image embedded as a HTML <a> tag (works best
# with browser-based clients). Mode 'caption' sends the image with the alt text
# as an MSC2530 caption (requires client support).
post_mode: split
# The interval to poll xkcd for new comics in.
poll_interval: 900
# The time to sleep between send requests when broadcasting a new xkcd comic.
# Set to 0 to disable sleep or -1 to run all requests asynchronously at once.
spam_sleep: 10
# Whether or not to allow !xkcd reindex.
# Disables itself after the command is used once.
allow_reindex: true
# Maximum number of search results
max_search_results: 10
# Base command without the prefix (!).
base_command: xkcd
